<?php

namespace backend\modules\products\controllers;

use backend\controllers\CRUDController;
use backend\models\Characteristic;
use backend\models\search\CharacteristicSearch;

/**
 * CharacteristicsController implements the CRUD actions for Characteristic model.
 */
class CharacteristicsController extends CRUDController
{
    /**
     * Init bean class
     */
    public function init()
    {
        $this->beanClass = Characteristic::className();
        $this->beanSearchClass = CharacteristicSearch::className();
        parent::init(); // TODO: Change the autogenerated stub
    }

}
